name: Mobs
version: 1.2.5 b21
author: coldandtired
main: me.coldandtired.mobs.Main
description: A fully-featured mob control plugin
softdepend: [Vault, WorldGuard, TerrainControl]
commands:
    spawn_mobs:
        description: Manually spawn some or all of the autospawns
        aliases: sm
        usage: "Usage: /spawn_mob (shortcut)"
permissions:
    mobs.can_spawn_mobs:
        description: Allows manual spawning
        default: op